# Generated by Django 3.2.16 on 2022-11-25 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Countrys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.TextField(verbose_name='Страна')),
                ('languages', models.TextField(verbose_name='Языки')),
            ],
        ),
        migrations.DeleteModel(
            name='Articles',
        ),
    ]
